//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace UPM_IPS.DNRDPVSQGProyectoMDD
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public abstract partial class ComponenteAccion
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateComponenteAccionMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Objetivo == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.DNRDPVSQGProyectoMDD.DNRDPVSQGProyectoMDDDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"ComponenteAccion", "", "Objetivo"),
						"DSL0001", this);
			}
		} // ValidateComponenteAccionMultiplicity
	} // class ComponenteAccion
} // UPM_IPS.DNRDPVSQGProyectoMDD

	
 