//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DNRDPVSQGProyectoMDD
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DDSProyMDD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DNRDPVSQGProyectoMDD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DNRDPVSQGProyectoMDDDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DNRDPVSQGProyectoMDDCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DNRDPVSQGProyectoMDDExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DNRDPVSQGProyectoMDDCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDNRDPVSQGProyectoMDDExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DNRDPVSQGProyectoMDDCommandSetId), 0x0001);
	
		// Package identifier
		public const string DNRDPVSQGProyectoMDDPackageId = "b22c0886-2fa7-4ded-b8ab-88c85c0dce5a";
		
		// Editor factory identifier
		public const string DNRDPVSQGProyectoMDDEditorFactoryId = "d33c21d7-05d2-4800-ae69-f7a9ab8c2d21";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DNRDPVSQGProyectoMDDModelExplorerToolWindowId = "36502145-4c3f-49e3-8b54-4db4b3daeff6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DNRDPVSQGProyectoMDD
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DNRDPVSQGProyectoMDDCommandSetId = "be0aad10-e16b-47b2-b04c-63e3fce933fb";
	}
}